hix_io:
    domain: 'hix.io'
    dev: true
    db_uri: 'postgres://hix_io@localhost/hix_io_dev'
mongrel2:
    configdb: 'etc/api.sqlite'
auth:
    provider: 'hostaccess'
hostaccess:
    - '10.0.0.0/8'
logging:
    __default__: 'warn (color)'
    hix_io: 'info (color)'
    loggability: 'warn (color)'
    configurability: 'debug (color)'
    strelka: 'warn (color)'

