hix_io:
    host: 'localhost'
    dev: true
    db_uri: 'postgres://hix_io@localhost/hix_io_dev'
mongrel2:
    configdb: 'etc/hixio.sqlite'
auth:
    provider: hixio
hix_io_auth:
    allowed_netblocks:
        - 127.0.0.1/32
        - 192.168.0.0/24
logging:
    __default__: 'warn (color)'
    hix_io: 'warn (color)'
    loggability: 'warn (color)'
    configurability: 'debug (color)'
    strelka: 'debug (color)'

