---
hix_io:
    host: 'localhost'
    db_uri: 'postgres://hix_io@localhost/db01'
    schema: 'hix_io_dev'
    dev: true

auth:
    provider: 'hixio'

mongrel2:
    configdb: 'etc/hix_io.sqlite'

sessions:
    session_class: 'db'

dbsession:
    connect: 'postgres://hix_io@localhost/db01'
    table_name: 'sessions'
    cookie_name: 'hix_io_session'
    expires: '+1d'

logging:
    __default__: 'warn (color)'
    hix_io: 'debug (color)'
    loggability: 'warn (color)'
    configurability: 'warn (color)'
    strelka: 'debug (color)'
